typography_spectrum: 0.21789392014034092
color:
  brandColors:
    - '#ffffff'
    - '#6892ba'
    - '#090a0e'
    - '#afc9e2'
    - '#7f0828'
  brandStrength: 0.3125
  lightness: 0.8001764181535691
  saturation: 0.3125
  rhythmicContrast: 0.46191071649082005
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.30872165015898645
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Acuícola S.A. '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Servicios Ambientales y de Ingeniería Acuícola
purpose: []
